---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
provisioner: fake-vendor/nfs-storage-provioner
reclaimPolicy: Delete
parameters:
  assetRoot: /mnt/nfs/
  defaultOwnerAssetUid: "1000"
  defaultOwnerAssetGid: "1000"
