#Docker image location and name
imageName: microk8s:32001/nfs-provisioner

#The catalog in docker container which correstponds assetRoot of host filesystem
innerAssetRoot: /pv

#The stucture based on which the storage class will be created in k8s
storageClass:
  name: nfs-storage
  isDefaultClass: false
  provisionerName: fake-vendor/nfs-storage-provisioner
  reclaimPolicy: Delete
  parameters:
    assetRoot: /mnt/nfs/
    defaultOwnerAssetUid: "1000"
    defaultOwnerAssetGid: "1000"

#The service's account detail behalf the provisoner will run in k8s
serviceAccount:
  name: pv-provisioner
  imagePullSecrets: []

#The name of the cluster role name. by default Release.Name is used
clusterRoleName: ""
#The name of the cluster role binding name. By default .Release.Name is used
clusterRoleBindingName: ""

podSecurityPolicyName: ""
