apiVersion: storage.k8s.io/v1
kind: StorageClass
{{- with .Values.storageClass }}
metadata:
  name: {{ .name | quote }}
provisioner: {{ .provisionerName | quote }}
reclaimPolicy: {{ .reclaimPolicy | quote }}
parameters:
  outerAssetRoot: {{ .parameters.outerAssetRoot | quote }}
  ownerNewAssetUid: {{ .parameters.ownerNewAssetUid | quote }}
  ownerNewAssetGid: {{ .parameters.ownerNewAssetGid | quote }}
{{ end }}