apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterRoleName | default .Release.Name | quote }}
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list","watch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list","watch"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list","watch","create", "update", "patch", "delete"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list","watch"]
