apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name | quote }}
  labels:
    {{- include "nfs-pv-provision.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "nfs-pv-provision.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nfs-pv-provision.selectorLabels" . | nindent 8 }}
    {{ $tag := .Chart.AppVersion }}
    spec:
      serviceAccountName: {{ include "nfs-pv-provision.serviceAccountName" . }}
      containers:
        - name: provisioner
          args:
            - serve
            - --storage-asset-root
            - {{ .Values.innerAssetRoot }}
            - --storage-classes
            - {{ include "nfs-pv-provision.storageClassesList" . }}
            - --v
            - "2"
          image: {{ .Values.imageName }}:{{ $tag }}
          volumeMounts:
          {{- $innerAssetRoot := .Values.innerAssetRoot}}
          {{- range .Values.storageClasses }}
            - mountPath: {{ list $innerAssetRoot .name | join "/" | quote}}
              name: {{ .name }}
          {{- end }}
      volumes:
      {{- range .Values.storageClasses }}
        - name: {{ .name }}
          {{- if contains ":" .parameters.assetRoot }}
          {{- $assetItems := split ":" .parameters.assetRoot }}
          nfs:
            server: {{ $assetItems._0 }}
            path:   {{ $assetItems._1 }}
          {{- else }}
          hostPath:
            path: {{ .parameters.assetRoot | quote }}
            type: Directory
          {{- end }}
      {{- end }}
      dnsPolicy: Default
