apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ .Values.podSecurityPolicyName | default .Release.Name | quote }}
  labels: {{ include "nfs-pv-provision.labels" . | nindent 4 }}
spec:
  privileged: false
  allowPrivilegeEscalation: true
  defaultAllowPrivilegeEscalation: true
  allowedFlexVolumes: []
  readOnlyRootFilesystem: false
  allowedCapabilities: []
  defaultAddCapabilities: []
  fsGroup:
    rule: RunAsAny
  hostIPC: false
  hostNetwork: false
  hostPID: false
  hostPorts: []
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - hostPath
    - secret
    - downwardAPI
    - nfs
  allowedHostPaths:
    {{- range .Values.storageClasses }}
    {{- /* To avoid NFS URLs to fall here */ -}}
    {{- if not (contains ":" .parameters.assetRoot) }}
    - pathPrefix: {{ .parameters.assetRoot }}
      readOnly: false
    {{- end }}
    {{- end }}
