apiVersion: v1
kind: ServiceAccount
{{- $namespace := .Release.Namespace }}
{{- with .Values.serviceAccount }}
metadata:
  name: {{ .name }}
  namespace: {{ $namespace | quote }}
{{- if .imagePullSecrets }}
imagePullSecrets:
{{- range .imagePullSecrets }}
- name: {{ . | quote }}
{{- end }}
{{ end }}
{{ end }}
