{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{ include "nfs-pv-provision.labels" . | nindent 4 }}
  name: {{ include "nfs-pv-provision.serviceAccountName" . }}
{{- if .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.serviceAccount.imagePullSecrets }}
- name: {{ . | quote }}
{{ end }}
{{ end }}
{{ end }}
