apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    {{- include "nfs-pv-provision.labels" . | nindent 4 }}
{{- with .Values.storageClass }}
  name: {{ .name | quote }}
  {{- if .isDefaultClass | default false }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: {{ .provisionerName | quote }}
reclaimPolicy: {{ .reclaimPolicy | quote }}
parameters:
  assetRoot: {{ .parameters.assetRoot | quote }}
  defaultOwnerAssetUid: {{ .parameters.defaultOwnerAssetUid | quote }}
  defaultOwnerAssetGid: {{ .parameters.defaultOwnerAssetGid | quote }}
{{ end }}
