apiVersion: v1
kind: Namespace
metadata:
  name: test-01

---
apiVersion: v1
kind: Namespace
metadata:
  name: test-02

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fake-storage-class
provisioner: fake-vendor/fake-storage-provioner
reclaimPolicy: Delete
parameters:
  outerAssetRoot: /mnt/efs/
  ownerNewAssetUid: "1000"
  ownerNewAssetGid: "1000"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: some-storage-class
provisioner: some-vendor/some-provioner
reclaimPolicy: Delete
parameters: {}
